name: brainrot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - cpuonly
  - pip
  - pip:
    - openai-whisper>=20231117
    - moviepy>=1.0.3
    - pysrt>=1.1.2
    - webvtt-py>=0.4.6
    - tqdm>=4.65.0
    - pydub>=0.25.1
    - ytdl>=1.0.0rc1
    - python-dotenv>=0.19.1
    - pyannote.audio>=2.0.1
    - opencv-python